baseURL = "https://severndelta.co.uk/"
languageCode = "en-gb"
title = "Severn Delta Limited"

[params.header]
    title = "Severn Delta"
    info = "Creator of Consumer Products"
    copyright = "2020 Severn Delta Limited"
